site_name: Notion User Documentation
nav:
  - Home: Annabelle-index.md
  - Creating a Notion Page: Ahmed-createAPage.md
  - Creating a Notion Calendar: Annabelle-createACalendar.md
  - Creating a Notion Database: Evann-createADatabase.md
  - Troubleshooting: Manraj-Troubleshoot.md
  - Glossary: Manraj-Glossary.md
theme: 
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: grey blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: 
  © 2024 <a href="https://github.com" target="_blank" rel="noopener">Ahmed Calif, Annabelle Chen, Evann Li, Manraj Bains</a>